# ==============================================================================
# PLANTILLA: Construcción (CI Build)
# VERSIÓN: 2.0.1
# DESCRIPCIÓN: Módulo reutilizable encargado de preparar el entorno Node.js,
#              optimizar tiempos mediante caché y descargar dependencias base.
# PARÁMETROS: 
#   - node-version (string): Versión de Node.js a utilizar.
# ==============================================================================
name: CI Build Template
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4: Extrae el código del repositorio
      - uses: actions/checkout@v4
      
      # actions/setup-node@v4: Configura el entorno y habilita caché nativa de NPM
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm' # Optimización clave para TTM
          
      # Instalación limpia basada en package-lock.json
      - name: Install dependencies (Build)
        run: npm ci