name: Main Workflow TechMarket
on:
  push:
    branches: [main, develop] # Estrategia multi-entorno
jobs:
  call-ci:
    uses: ./.github/workflows/build-template.yml
    with:
      node-version: '20'
  call-cd:
    needs: call-ci
    if: github.ref == 'refs/heads/main' # Solo despliega si es la rama main
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit # Pasa los secretos automáticamente